### ISSUE TITLE
Build tutorial

### ISSUE THREAD

**Issue by LatinSuD** [sentialx/multrin#18]
Hi, i'm a little newbie to Node.JS and Yarn, so these are some steps not yet covered in installation instructions (Windows 10 here):

* Yarn needs be installed.

* At some point it required and Elevated Powershell (i don't remember which one).

* Requires a Github personal token (with no special privileges).
On the shell before running yarn:
set GH_TOKEN=....

**Comment by sentialx** [comment]
The GH_TOKEN is required when you want to publish a release, not for users. Just ignore the errors, it will build properly.

**Comment by sentialx** [comment]
Fixed.
