### ISSUE TITLE
Allow to rename Multrin window

### ISSUE THREAD

**Issue by LatinSuD** [sentialx/multrin#19]
It would be nice if you could rename window names, so I can tell a Multrin instance from another.

I currently have taskbar on the left, so I can read the text of every window.

There are hacky ways to do it, like with Autohotkey, but that's not the point.

**Comment by sentialx** [comment]
Very good point! Thanks!

**Comment by juanferrer** [comment]
Is anyone working on this? Might want to prepare a pull request.

**Comment by DaKie206** [comment]
It would be cool too, if you could change the icon in the taskbar.
