### ISSUE TITLE
If switching to an app from an external source (such as tray icons) the window will become focused, but multrin's tabs don't update.

### ISSUE THREAD

**Issue by CoreParadox** [sentialx/multrin#2]
First, awesome app! 

Second, the bug: Say I group slack into multrin with another window, then click the tray icon for slack, slack becomes focused, but multrin sill thinks the other window is selected, so I have to click the slack tab, THEN click the other tab.

Example:
![image](https://user-images.githubusercontent.com/6187665/53363277-b0794980-3901-11e9-9035-3ac7ec9ac12a.png)

**Comment by sentialx** [comment]
Could you reproduce it in a GIF? I need to see this behavior.

**Comment by sentialx** [comment]
Okay, I was able to reproduce this by myself, thanks!
