### ISSUE TITLE
A javascript error occurred in the main process

### ISSUE THREAD

**Issue by maravento** [sentialx/multrin#20]
A javascript error occurred in the main process
Windows 7 Sp1 x64
![VirtualBox_W7_18_03_2019_13_45_37](https://user-images.githubusercontent.com/14880802/54555302-70e3d180-4984-11e9-8c08-24ca0c1c84ce.png)

**Comment by sentialx** [comment]
Oh, that's because of the GetScaleFactorForMonitor api is supported from Windows 8.1. Thanks for your issue, will fix.
