### ISSUE TITLE
无法调整主窗口的大小

### ISSUE THREAD

**Issue by ArnoFranklin** [sentialx/multrin#27]
我加入了多个应用进入窗口，当我缩小窗口直至超过了其中一个应用的最小窗口限制时，multrin 会自动把窗口锁定成一个固定尺寸，我无法再次修改 multrin 的窗口大小。

是否可以动态适应不同的应用大小呢？切换窗口时，不会改变某个应用的大小？

感谢你们的工作!

**Comment by sentialx** [comment]
Could you write it in English? Thanks

**Comment by ccdalao** [comment]
Unable to resize main window,We need this feature.
