### ISSUE TITLE
Add support for 32 bit systems

### ISSUE THREAD

**Issue by nwdxlgzs** [sentialx/multrin#29]
Excuse me, what is the reason for the failure to release i32?What is the cause of the error when generating 32 bits?

**Comment by sentialx** [comment]
Multrin uses uint64 structs which aren't supported by Windows x86 arch.

**Comment by nwdxlgzs** [comment]
Well, you can only hope that the user is a 64-bit system. Since it can't be changed, I hope you can improve it. This application is so creative!

**Comment by jcotton42** [comment]
You can most certainly use that datatype on 32-bit Windows

**Comment by sentialx** [comment]
@jcotton42 Thanks for info. I will consider trying to release Multrin for 32 bit systems.

**Comment by sentialx** [comment]
Fixed.
