### ISSUE TITLE
Some minor issues related to DPI scaling

### ISSUE THREAD

**Issue by yuzukki** [sentialx/multrin#3]
First, awesome app!

Second, my display resolution is 3840x2160, DPI scale is 150%.
multrin window display is clear, but there is something wrong, see the gif
![multrin-gif](https://user-images.githubusercontent.com/33631658/53391478-6f506a80-39d1-11e9-83c9-21c9dbb1fdb9.gif)
There have been some dislocations. multrin does not work properly.

If I change the multrin compatibility, "Change high DPI settings"→ "High DPI scaling override" to System. Multrin is working properly. But the window display is blur and so is the font.

**Comment by MiracleXYZ** [comment]
My display settings are 1920x1080 and 150% and I'm still having this issue.

**Comment by sentialx** [comment]
Thank you for opening an issue, will investigate this.

**Comment by Jack-Works** [comment]
2736x1824 and 200%, also having this issue

**Comment by jonathontoon** [comment]
Also can confirm this is happening on a Dell XPS 15, 3840 x 2160 at 200%. Running Windows 10.0.17763.

Regardless, great idea, keep it up. Can't wait to see the improvements!

**Comment by sentialx** [comment]
I'm kinda surprised that win32 doesn't bother about the scaling when moving and resizing a Window to a specified bounds. It looks I will need to get the system scaling and calculate it by myself.

**Comment by tahaemin** [comment]
I'm facing this issue when i use a hdmi connected monitor which has different resolution with my built in monitor. Maybe it is about Windows 10 or Electron because i saw errors like this on other apps which are compiled with Electron.
