### ISSUE TITLE
Version 0.3.3 has problems with Chinese labels

### ISSUE THREAD

**Issue by wwminger** [sentialx/multrin#33]
Version 0.3.3 has problems with Chinese labels, and Chinese will become garbled.
And it has the same problem with notation.
The system is win10 x64
![image](https://user-images.githubusercontent.com/10833243/58769760-ba83a600-85dc-11e9-9095-159f71e6d252.png)

**Comment by chenyuanqi** [comment]
Me too.

**Comment by ruibaby** [comment]
Me too.

**Comment by zerelazero** [comment]
The same problem
