### ISSUE TITLE
Unable to Yarn Dev 

### ISSUE THREAD

**Issue by yclim95** [sentialx/multrin#36]
Unable to run command `yarn dev`

**`yarn run v1.16.0`
error Command "dev" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.**

I am just wondering how to resolve this issue

**Comment by sentialx** [comment]
Well, I don't use yarn anymore. Try using npm run dev

**Comment by sentialx** [comment]
What is your working directory? Are you running it in Multrin dir?

**Comment by yclim95** [comment]
Oh ok .. so I have to create a folder for Multrin 
Then only I use this command 
**`$ npm i -g windows-build-tools`**

**Comment by yclim95** [comment]
What is your working directory? Are you running it in Multrin dir?

How should I solve this ?

**Comment by sentialx** [comment]
I'm running it in Multrin directory.

**Comment by yclim95** [comment]
Is this line of code Multrin directory ?

`**npm i -g windows-build-tools**`

**Comment by yclim95** [comment]
Do I need to create a folder first before Entering this code ?
`**$ npm i -g windows-build-tools**`

**Comment by yclim95** [comment]
I am not sure how you create by using the code ?? would love to know the process?? 

1) Do you need to create a Multrin Directory? 
In the Multin Directory, Enter this code ? 

2)` **npm i -g windows-build-tools**
`
3) `**npm run dev**`
