### ISSUE TITLE
Chrome window doesn't scale to 100% in size

### ISSUE THREAD

**Issue by mittalyashu** [sentialx/multrin#4]
![multrin_54hrpff9ea](https://user-images.githubusercontent.com/29014463/53438933-f11eb300-3a26-11e9-94e1-10323f2d3323.png)

When I click on maximize icon, chrome get detach from the application itself and as you can see in the image, it also have some kind of black border around it.

**Comment by sentialx** [comment]
The black border around is the result of removing WS_SIZEBOX style from window to prevent resizing.

**Comment by mittalyashu** [comment]
I see 🤔

**Comment by sentialx** [comment]
Are you clicking Chrome's maximize button or Multrin's one?

**Comment by mittalyashu** [comment]
Chrome maximize button

**Comment by sentialx** [comment]
Unfortunately, this is an expected behavior. When the window's bounds change, it will get detached.
