### ISSUE TITLE
Positioning of app in multi monitor setup with different scalings

### ISSUE THREAD

**Issue by davidLeimroth** [sentialx/multrin#47]
Version: 0.4.1
OS: Windows 10
Hardware: Dell Latitude + Universal Dock + external displays

The positioning of of apps on the notebooks screen (with 1920x1080 at 125%) isn't correct.
Scaling to 100% fixes the positioning, but makes everthing to small to read.

![2019-06-19 10_31_26-Window](https://user-images.githubusercontent.com/23295037/59750457-2a518c00-927f-11e9-8183-56d74574705f.png)

Seems related to https://github.com/sentialx/multrin/issues/3

**Comment by erikbcox** [comment]
Version: 0.4.1
OS: Windows 10
Hardware: Thinkpad + Universal Dock + 2 external displays

Child app offset to left of multrin container app

![image](https://user-images.githubusercontent.com/1831095/60595526-cc3ba300-9d6c-11e9-9526-a1fb95ffe91d.png)

When maximized the offset portion of the child app is off screen. 

![image](https://user-images.githubusercontent.com/1831095/60595619-f42b0680-9d6c-11e9-94fa-be22f89eb86e.png)

**Comment by sentialx** [comment]
Merging into #96
