### ISSUE TITLE
Submerge navbar into application navbar

### ISSUE THREAD

**Issue by mittalyashu** [sentialx/multrin#5]
This feature request might take a long run to complete but worth of shot.

Every application has its own header, and using the application for example Visual Studio Code inside Multirun can take a lot of space in the header.

![chrome_g3ps1dww5s](https://user-images.githubusercontent.com/29014463/53439279-b49f8700-3a27-11e9-8121-2676c9c1da71.png)

![multrin_elhqe7erkc](https://user-images.githubusercontent.com/29014463/53439291-bbc69500-3a27-11e9-80d7-e33962bb5d62.png)

Same goes for any other application, the idea is to merge the application header and Multirun header together so that it can occupy less space.

Also having these button at two places is also kinda weird.

![image](https://user-images.githubusercontent.com/29014463/53439393-efa1ba80-3a27-11e9-97d7-ffde519c85e7.png)

**Comment by sentialx** [comment]
I was trying to do this, but unfortunately I can't remove the caption bar from a frameless window, since it is part of the app's DOM, for example vscode.

**Comment by mittalyashu** [comment]
Nice

**Comment by sentialx** [comment]
Closing it as won't fix.
