### ISSUE TITLE
Error: The specified module can not be found.

### ISSUE THREAD

**Issue by Fasguy** [sentialx/multrin#51]
This pops up as soon as i start Multrin
![image](https://user-images.githubusercontent.com/9297451/60005304-839a3080-966e-11e9-9652-a4e2e5fa3f19.png)

I tried reinstalling a few times and the portable version also has the same problem.

**Comment by sentialx** [comment]
What OS do you use?

**Comment by Fasguy** [comment]
Windows 10 1903/19H1.
Just freshly installed the entire system.

**Comment by sentialx** [comment]
Is your system 32 or 64 bit?

**Comment by Fasguy** [comment]
64Bit

**Comment by sentialx** [comment]
That's weird, it doesn't happen to me.

**Comment by Fasguy** [comment]
Are there any additional dependencies i need to install?
I'm not too familiar with node.js, i've only used it to make a Discord Bot.

**Comment by sentialx** [comment]
Well, if you're using Multrin's binary, you don't need to install anything.

**Comment by Fasguy** [comment]
Then i'm at a loss as to why the error appears.
