### ISSUE TITLE
Can only add Chrome into Multirin window

### ISSUE THREAD

**Issue by ysong62** [sentialx/multrin#52]
Try on both 0.4.1 and 0.4 version with all softwares I'm using on a Windows 10 1809 PC.
Multirin only showed top task bar when I moved a chrome window on it, which means only chrome can be added.

**Comment by sentialx** [comment]
Try dragging other apps on the tabbar.

**Comment by ysong62** [comment]
Yes I dragged all windows on the tabbar just like the gifs showed on every website talking about Multirin, but just not working, even IE or Resource Manager also not working.
