### ISSUE TITLE
I can't finish script "yarn"

### ISSUE THREAD

**Issue by kungua** [sentialx/multrin#63]
os version: windows 10
node version: v10.4.0
npm version: 6.1.0
python version: 2.7.15
first, i run 'npm i -g windows-build-tools' no warning no error
![image](https://user-images.githubusercontent.com/52815012/61193128-1701d700-a6ec-11e9-8baa-01059f88da99.png)
and then when i run 'yarn' i met this error
![image](https://user-images.githubusercontent.com/52815012/61193149-3dc00d80-a6ec-11e9-9bed-dac67064ce9a.png)

**Comment by sentialx** [comment]
Hi, I suggest you to install Node.js 12 and use `npm install` instead of `yarn`.
