### ISSUE TITLE
Multrin minimizes without currently open app

### ISSUE THREAD

**Issue by Saderius** [sentialx/multrin#64]
**Bug description**
When I minimize Multrin on any app that particular app stays on where it was, but Multrin minimizes anyway.

**Expected behavior**
Multrin minimizes with a particular app that is currently open.

**Screenshots**
There's a link embed in image to gif.

[![](https://i.imgur.com/V1NReus.jpg)](https://i.imgur.com/bFZSddB.gif)

**Details:**
 - Operating System: **Windows 10 Pro, Version 10.0.18362 Build 18362**
 - Multrin version: **latest (downloaded today)**
 - Last known working Multrin version: **none**

**Additional context**
Aaand it seems like clicking on Multrin icon in windows taskbar to minimize it works perfectly fine.

**Comment by sentialx** [comment]
Fixed (I don't remember the commit hash).
