### ISSUE TITLE
Color themes for apps

### ISSUE THREAD

**Issue by Saderius** [sentialx/multrin#68]
What I mean by that is an option to choose between dark/light theme for an particular app. For example:
- dark Github, but light File Explorer;
- dark Discord, but light Mindboard;
- etc.

Also it would be great to use Windows acrylic with current scheme and option to pick a background color depending on an app (just like it is right now with tabs).

____________
BTW. Found this project today via electron page. Gotta say that I **Absolutely** **L O V E** it. I really miss [Sets](https://youtu.be/WZl2MOzUASY) integrated with Edge and other Windows app that were [removed from insider builds](https://www.theverge.com/2019/4/23/18512250/microsoft-windows-10-sets-feature-app-tabs-removal). If you need a QA or designer just give me a call.

**Comment by sentialx** [comment]
Hi, thanks for your issues. Unfortunately it won't be possible to control apps themes.
