### ISSUE TITLE
Discord can be resized outside of Multrin's window

### ISSUE THREAD

**Issue by taydev** [sentialx/multrin#7]
![image](https://user-images.githubusercontent.com/35742552/53507335-9aa98700-3aaf-11e9-8c19-968dbae13123.png)

Steps to reproduce:
1 - Drag Discord into Multrin's window
2 - Try to resize Multrin horizontally
3 - Discord resizes outside of Multrin

Note: I have not tried this with other applications, however Firefox appears to be fine (there's a white border around the window from Multrin that prevents you from resizing it, and Discord doesn't have this white border). The Discord window also apparently resets itself when moving the main Multrin window.

EDIT: This bug also affects Spotify, but not Windows' File Explorer and IntelliJ IDEA. Perhaps this is an issue with Electron apps?

**Comment by sentialx** [comment]
Thank you for opening issue! This issue is not with Electron apps. It's an issue with the window's min width and height, but I'm kinda surprised, because I was testing it and it worked. Will investigate this further.

**Comment by sentialx** [comment]
Sorry, this is a frameless window issue, my mistake.
