### ISSUE TITLE
Collapse default windows titlebar

### ISSUE THREAD

**Issue by Sieabah** [sentialx/multrin#72]
**Is your feature request related to a problem? Please describe.**
Would it be possible to either manually or automatically detect if it uses the default task bar to just collapse it? I have pictures below which I think may explain what I mean.

**Describe the solution you'd like**
To be able to full screen and remove the window bar from the top if I choose to.

**Additional context**
![image](https://user-images.githubusercontent.com/650333/62927931-5dd70100-bd6c-11e9-9b7a-c73e54e5ae47.png)

![image](https://user-images.githubusercontent.com/650333/62927980-77784880-bd6c-11e9-81c2-cbe21cb6bcea.png)

**Comment by sentialx** [comment]
Unfortunately this is not possible without injecting a DLL to a window (doing that by just using SetWindowLong is very buggy). Also, the next update will introduce windows splitting, so they must have titlebars. Closing as wontfix.
