### ISSUE TITLE
Don't globally capture ctrl-tab

### ISSUE THREAD

**Issue by Sieabah** [sentialx/multrin#75]
**Bug description**
Opening multrin makes it so no other program can capture ctrl-tab. This interferes with web browsers, I've found this issue on two machines and closing multrin causes the error to go away.

**To Reproduce**
Open multrin and use a web browser and try to ctrl-tab

**Expected behavior**
I should be able to ctrl-tab within multrin and outside of multrin.

**Details:**
 - Operating System: Windows
 - Multrin version: 1.0.0

**Comment by Sieabah** [comment]
This is the offending line, I think it should only be available is multrin is the focused window.

https://github.com/sentialx/multrin/blob/adf31d3c6980b8d3efc0b071306cce4f92eb003e/src/main/windows/app.ts#L155

**Comment by DaKie206** [comment]
Would be good if it would be another shortcut to change multrin tab

**Comment by Sieabah** [comment]
Or that it doesn't capture and reject ctrl-tab. I effectively can't have this running because I can't change tabs in my browser...

**Comment by BanCrash** [comment]
I were going to report the same issue. So +1 from here. 

But I just installed it and I love it. Hope this will get fix soon so I can fully use it!

**Comment by Sieabah** [comment]
Last update was four months ago so it's probably safe to say it's abandoned.

**Comment by sentialx** [comment]
@Sieabah This project will be still maintained however, I don't have enough time at the moment.

**Comment by Sieabah** [comment]
@sentialx Not having enough time to maintain means that it's unmaintained/abandoned. It's fine, this issue was a showstopper, as I use ctrl-tab to switch browser tabs and switch between files so I had to uninstall it to be able to use my system.

**Comment by sentialx** [comment]
I will see what I can do about this issue

**Comment by BanCrash** [comment]
The issue is solved now, Thanks you!!

Now I have a suggestion to do, but IMO nothing important. Just add also compatibility with Ctrl + Shift + Tab so we can navigate among the tabs as in the navigators.
