### ISSUE TITLE
Doesn't work with 250% DPI

### ISSUE THREAD

**Issue by DrPepperBianco** [sentialx/multrin#77]
**Bug description**
When DPI is 250% (for example an a Surface Book) it doesn't work at all. Moving Windows inside the Multrin Window has no effect.

**To Reproduce**
Use a high resolution (e.g. 3000x2000 on the Surface Book) and set DPI to 250%. To set System DPI also, log off and on again.
Now behaviour can be observed.

**Expected behavior**
It should work, like it does with 100% DPI.

**Details:**
 - Operating System: Windows 10 1903
 - Multrin version: 1.0.0
 - Last known working Multrin version: n/a

**Comment by tan-wei** [comment]
`multrin` does not work well in the second screen whose DPI is different from the first screen. Maybe it is the same issue.
My Surface Pro6 is a high resolution screen (which is always the first screen), the second screen is a noraml one which is connected with HDMI. `multrin` works well in the first screen, however, it behaves quite wired: quite small window, can't be maximized ... Is there any necessary upload a screen shot or video? Thanks!
