### ISSUE TITLE
Releasing tab to Window

### ISSUE THREAD

**Issue by DaKie206** [sentialx/multrin#78]
I would like to release a `multrin` tab into the normal window
I don't know if iI just didn't find the feature or if it is not existing.

**Comment by sentialx** [comment]
Try dragging the attached window titlebar out of Multrin window.

**Comment by DaKie206** [comment]
This isn't working for me. When I try to drag it out of `multrin` it looks first looks like its back in the normal window but when I minimize and maximize `multrin` again it is still open in multrin. Furthermore it would be good to have an rightclick option to release the window while having multrin maximized.

**Comment by sentialx** [comment]
@DaKie206 Could you record it?

**Comment by DaKie206** [comment]
https://photos.app.goo.gl/RPfhayzp8TzecF298

**Comment by sentialx** [comment]
Okay, that's a scaling issue.
