### ISSUE TITLE
Tabbed Windows Explorer

### ISSUE THREAD

**Issue by jesse9212** [sentialx/multrin#82]
Would be nice if I could eventually use this as a tabbed Windows Explorer replacement.

It would have to automatically add apps (in this case explorer.exe) as new tabs.

**Comment by CiriousJoker** [comment]
Same here, this would be sick

**Comment by enoversum** [comment]
+1, that's the main thing I am looking for as well :) !

**Comment by guillaume86** [comment]
+1, I don't even need/want the other features, I would pay for a good integration of chromium tabs into windows explorer.
