### ISSUE TITLE
Crashes On Darwin

### ISSUE THREAD

**Issue by sajjaadf** [sentialx/multrin#85]
Crashes on MacOS when window dragged. (broken)
[Kapture 2019-10-21 at 12.20.38.mp4.zip](https://github.com/sentialx/multrin/files/3752521/Kapture.2019-10-21.at.12.20.38.mp4.zip)
Video As Zip
**Details:**
 - Operating System: 10.15
 - SIP enabled

**Comment by sentialx** [comment]
It seems Apple changed something in macOS Catalina. The APIs which Multrin uses on macOS are unstable, but that's the only way to manage windows. I think I might need some help in finding the problem with the new update.

**Comment by sajjaadf** [comment]
ah

**Comment by sentialx** [comment]
Why have you closed this issue?

**Comment by sentialx** [comment]
Fixed in v1.1.0
