### ISSUE TITLE
some softs should be ruled out

### ISSUE THREAD

**Issue by Kert-Zhang** [sentialx/multrin#87]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

multrin is used in full screen mode,when i run  and click  another soft， the soft is merged into multrin very easily，however，i do'nt  want this。 i would like that some softs should be ruled out。 thank you.

**Describe alternatives you've considered**

**Additional context**

**Comment by sentialx** [comment]
I can't understand. What do you have in mind exactly?

**Comment by Excigma** [comment]
My interpretation is that OP wants a feature to blacklist certain "soft[ware]" (programs?) from being added into Multrin
