### ISSUE TITLE
Show multrin window icon in task bar

### ISSUE THREAD

**Issue by DaKie206** [sentialx/multrin#91]
**Describe the solution you'd like**
I would like to see the icon of the `multrin` window in the taskbar

**Comment by sentialx** [comment]
Could you describe it more precisely?

**Comment by DaKie206** [comment]
When I set an icon for my `multrin` window I would like it to show up in the taskbar too.
Like GIMP shows the current drawing in the taskbar.

**Comment by sentialx** [comment]
@DaKie206 I'm able to change the icon... 
![image](https://user-images.githubusercontent.com/11065386/70862549-1e007000-1f3e-11ea-9582-1300ff4ff7c5.png)

**Comment by DaKie206** [comment]
For me that doesn't work: 
![image](https://user-images.githubusercontent.com/50425705/70862590-9c5d1200-1f3e-11ea-80bc-8de5e62414d5.png)
It also isn't showing the content of the window

**Comment by sentialx** [comment]
Closing it as wontfix
