### ISSUE TITLE
Relased window not showing up in taskbar

### ISSUE THREAD

**Issue by DaKie206** [sentialx/multrin#95]
**Bug description**
After releasing a window I have to open it again before it shows up in the taskbar

**Expected behaviour**
Showing up in the taskbar immediately

**Details:**
 - Operating System: Windows 10 home 1909
 - Multrin version: 1.1.1
 - Last known working Multrin version: -
 - Scaling (in percentage, if present): 125%

**Additional context**

**Comment by sentialx** [comment]
@DaKie206 For now you can try focusing other window and then your detached app.
